### ISSUE TITLE
Any hope of getting this updated to Haxe 4.2.3

### ISSUE THREAD

**Issue by tupini07** [YellowAfterlife/hxpico8#2]
I like playing around with Pico8, and one of the things I often find myself wishing for is to be able to have a typing system. Using Haxe for Pico8 seems like a great idea, since it has a great typing system and wonderful IDE support. 

I tried using this library with the latest Haxe release (4.2.3) and it is giving me some errors. I tried fixing the issues that came up but sadly I'm not proficient enough with Haxe (and custom compilation targets) to tackle the issue.

These are the issues I get:

```log
haxe/current/lib/hxpico8/git/Map.hx:33: characters 34-43 : Warning : This typedef is deprecated in favor of Unknown<0>
haxe/current/lib/hxpico8/git/Map.hx:52: characters 56-65 : Warning : This typedef is deprecated in favor of haxe.IMap<IMap.K, IMap.V>
haxe/current/lib/hxpico8/git/Map.hx:55: characters 50-59 : Warning : This typedef is deprecated in favor of haxe.IMap<IMap.K, IMap.V>
haxe/current/lib/hxpico8/git/Map.hx:58: characters 65-74 : Warning : This typedef is deprecated in favor of haxe.IMap<IMap.K, IMap.V>
haxe/current/lib/hxpico8/git/Map.hx:61: characters 53-62 : Warning : This typedef is deprecated in favor of haxe.IMap<IMap.K, IMap.V>
haxe/current/std/eval/_std/haxe/Exception.hx:18: characters 10-18 : Class<Std> has no field isOfType
haxe/current/std/eval/_std/haxe/Exception.hx:26: characters 10-18 : Class<Std> has no field isOfType
haxe/current/std/haxe/ds/EnumValueMap.hx:58: characters 18-26 : Class<Std> has no field isOfType
haxe/current/std/haxe/ds/EnumValueMap.hx:58: characters 45-53 : Class<Std> has no field isOfType
haxe/current/lib/hxpico8/git/Std.hx:13: lines 13-21 : Missing field downcast required by core type
```

**Comment by YellowAfterlife** [comment]
Ideally would need to rewrite this from scratch (using `sfhx` like I have with `sfgml`) - I started doing so at some point, but the library had always been exotic at best, so I've not gotten too far with that

**Comment by tupini07** [comment]
Oh well, no worries. Thanks for answering :) I'll go ahead close this issue
